### ISSUE TITLE
ftdetect and filetype functions / commands: why not just global configuration?

### ISSUE THREAD

**Issue by sim590** [Konfekt/vim-mutt-aliases#2]
First, thanks for working on this code which is quite useful.

Concerning the usage of `ftdetect`, I don't think that the usage is correct here. Normally, `ftdetect/*` files should be used to **detect** file types which are not detected by default. For example, see [this file][pyrex] which tells how to detect the filetype `pyrex` which is not detected by default by Vim. The code written in `ftdetect/muttaliases.vim` doesn't do anything similar. Therefore, I think that this code should at least be moved from this file to `ftplugin/mail.vim` which would be loaded upon setting `ft=mail` which is done automatically by Vim when entering a mail file after begin launched by Mutt.

However, I don't think the any of the above or what is already in place is even best. I think that completion functionality should be available in all file types. I find it useful to complete mailing addresses in markdown files or other types of files. May be a combination of the two ideas could be used:

* Automatic `mail` filetype setting should be used to trigger the configs;
* Also, there should be a command (and/or a mapping) that one could use to enable mail completion in the current buffer through `CTRL+X CTRL+U`. Something like `:MailCompleteOn`.

What do you think?

[pyrex]: https://github.com/sim590/dotfiles/blob/thinkpad/vim/ftdetect/pyrex.vim

**Comment by Konfekt** [comment]
The latest commit takes up some of your suggestions. Could you test ride it and tell me what you think about it?

**Comment by sim590** [comment]
> The latest commit takes up some of your suggestions. Could you test ride it and tell me what you think about it?

I have just looked at your code and it seems good. I like the approach of letting the user set the global variable to include more filetypes. Good stuff! :smile:

I will close this issue now.
